put http://localhost:3000/update/update-packages

###
GET  http://localhost:3000/update/transaction?phoneNumber=254796869402

###
POST  http://localhost:3000/whatssap

###
GET http://localhost:3000/router

###
GET http://localhost:3000/phone

###
POST http://localhost:3000/api/jwt
Content-Type: application/json

{
    "phoneNumber" : "254740531659",
    "mac" : "10.xxx.xxx"
}
###
GET http://localhost:3000/tokens/phone?number=254726414